name: Deploy to EC2 via SSH

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: SSH & Deploy to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
            # Create venv if it doesn't exist
            if [ ! -d ".venv" ]; then
              python3 -m venv .venv
            fi

            # Activate venv and install dependencies
            source .venv/bin/activate
            .venv/bin/pip install --upgrade pip
            .venv/bin/pip install -r requirements.txt

            # Restart using full path to pm2
            export PATH=$PATH:/home/ubuntu/.npm-global/bin
            pm2 restart chatbot-app
